### ISSUE TITLE
Enable named capture groups with a new RegExp flag

### ISSUE THREAD

**Issue by pgilad** [tc39/proposal-regexp-named-groups#3]
instead of allowing them only in unicode regex, and to ensure backwards compatibility, the named capture groups can be turned on via a new RegExp flag

Maybe `/k` ?

**Comment by littledan** [comment]
Interesting suggestion. Would you need this flag if you use a Unicode RegExp?

**Comment by mathiasbynens** [comment]
https://github.com/littledan/es-regexp-named-groups#backwards-compatibility-of-new-syntax

I strongly disagree with this suggestion. Introducing new flags has a cost, and should only be done when really necessary. RegExps with the `u` flag set can be extended with new syntax [in a backwards compatible way](https://github.com/littledan/es-regexp-named-groups#backwards-compatibility-of-new-syntax) so no new flag is needed IMHO.

> instead of allowing them only in unicode regex

Why would you _not_ use the `u` flag for new regular expressions?

**Comment by pgilad** [comment]
I suggested it because according to author this cannot be used safely (without breaking backwards compat.) with non-unicode regexp, but if everyone intends to use the `u` flag then another new flag is redundant

**Comment by littledan** [comment]
I don't think we'll use a new flag; we'll probably use one of the options described at https://github.com/tc39/proposal-regexp-named-groups/issues/7
