### ISSUE TITLE
Advanced to stage 4

### ISSUE THREAD

**Issue by adrianheine** [tc39/proposal-regexp-named-groups#41]
See https://github.com/rwaldron/tc39-notes/blob/master/es8/2017-11/nov-28.md#9if-regexp-named-captures-status-update, PR is at tc39/ecma262#1027.

**Comment by FranklinYu** [comment]
So this issue is closed by d73854fcfd66746a2576d602e320cc4b28ebf31d?

Would stage-4 proposals be archived? They are already in ECMA-262.

**Comment by mathiasbynens** [comment]
@franklinyu Correct. This issue can be closed.
